'use strict';

function bind(context) {
    const { socket, user, io, db, stats, Deck, config, runtime, tableService, syncRecentVoices } = context;
    const { PHASES, STANDARD_BLIND_LEVELS, SNG_BUYIN_TIERS, BUYIN_RATE, CASHOUT_RATE, RUNIT_MAX, EXTRA_MAX, EXTRA_STEP, ACTION_TIME, gameBB, sngPrize } = config;
    const { roomGames, lobbySockets } = runtime;
    const { projectedPositions, clearStraddleDecision, emitStraddleOffer, showStraddleDecision, prepareNextStraddleDecision, cancelVisibleStraddleForTurn, maybeShowStraddleAfterAction, broadcastState, listSpectators, listRooms, broadcastRoomList, clampInt, genRoomId, genJoinCode, createRoomInvite, findRoomByInviteToken, findRoomByJoinCode, emitRoomInviteInfo, clientIp, recentFailures, codeAttemptLimited, recordCodeFailure, clearUserCodeFailures, canAuthorizeNewUser, authorize, activePlayers, canAct, isBettingRoundComplete, clearActionTimer, startActionTimer, afterAction, advanceStage, resolveRunIt, startHand, beginPlay, tryStartHand, liveCount, scheduleNextHand, scheduleEmptyCleanup, endCashTable, extendTable, chargeRebuy, removeBustedPlayers, joinAsSpectator, occupiedSeats, firstFreeSeat, seatPlayer, standUpPlayer, restoreVacatedPlayer, doShowdown, dealCommunity, recordAction, buildRanking, sendMatchResult, requestConfigChange, claimToken, declineToken } = tableService;
    return { socket, user, io, db, stats, Deck, config, runtime, tableService, syncRecentVoices, PHASES, STANDARD_BLIND_LEVELS, SNG_BUYIN_TIERS, BUYIN_RATE, CASHOUT_RATE, RUNIT_MAX, EXTRA_MAX, EXTRA_STEP, ACTION_TIME, gameBB, sngPrize, roomGames, lobbySockets, projectedPositions, clearStraddleDecision, emitStraddleOffer, showStraddleDecision, prepareNextStraddleDecision, cancelVisibleStraddleForTurn, maybeShowStraddleAfterAction, broadcastState, listSpectators, listRooms, broadcastRoomList, clampInt, genRoomId, genJoinCode, createRoomInvite, findRoomByInviteToken, findRoomByJoinCode, emitRoomInviteInfo, clientIp, recentFailures, codeAttemptLimited, recordCodeFailure, clearUserCodeFailures, canAuthorizeNewUser, authorize, activePlayers, canAct, isBettingRoundComplete, clearActionTimer, startActionTimer, afterAction, advanceStage, resolveRunIt, startHand, beginPlay, tryStartHand, liveCount, scheduleNextHand, scheduleEmptyCleanup, endCashTable, extendTable, chargeRebuy, removeBustedPlayers, joinAsSpectator, occupiedSeats, firstFreeSeat, seatPlayer, standUpPlayer, restoreVacatedPlayer, doShowdown, dealCommunity, recordAction, buildRanking, sendMatchResult, requestConfigChange, claimToken, declineToken, startRoundIfNeeded: tableService.startRoundIfNeeded };
}

module.exports = { bind };
